package utils

import (
	"bufio"
	"os"
	"regexp"
)

// IsGeneratedFile универсально определяет, является ли файл сгенерированным,
// проверяя первые N строк на наличие типового комментария (Go/Python/прочие).
// Если check == false — немедленно возвращает false.
func IsGeneratedFile(path string, check bool) (bool, error) {
	if !check {
		return false, nil
	}

	f, err := os.Open(path)
	if err != nil {
		return false, err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	linesToCheck := 10

	// Ищем распространённые маркеры генерации (без учёта регистра):
	// "code generated", "auto generated", "generated by" и обязательно "do not edit"
	// Поддерживаем начальные комментарии //, #, /*
	re := regexp.MustCompile(`(?i)^(//|#|/\*)\s*(auto\s*-?\s*generated|code\s*-?\s*generated|generated\s+by).*do\s+not\s+edit`)

	for i := 0; i < linesToCheck && scanner.Scan(); i++ {
		line := scanner.Text()
		if re.MatchString(line) {
			return true, nil
		}
	}
	if err := scanner.Err(); err != nil {
		return false, err
	}
	return false, nil
}
