package utils

import (
	"os"
	"path/filepath"
	"testing"
)

func TestIsGeneratedFile_Disabled(t *testing.T) {
	dir := t.TempDir()
	f := filepath.Join(dir, "x.go")
	_ = os.WriteFile(f, []byte("package x\n// Code generated DO NOT EDIT."), 0o600)
	got, err := IsGeneratedFile(f, false)
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	if got {
		t.Fatalf("expected false when check disabled")
	}
}

func TestIsGeneratedFile_GoMarker(t *testing.T) {
	dir := t.TempDir()
	f := filepath.Join(dir, "x.go")
	_ = os.WriteFile(f, []byte("// Code generated by tool. DO NOT EDIT.\npackage x\n"), 0o600)
	got, err := IsGeneratedFile(f, true)
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	if !got {
		t.Fatalf("expected true for go generated marker")
	}
}

func TestIsGeneratedFile_PythonMarker(t *testing.T) {
	dir := t.TempDir()
	f := filepath.Join(dir, "x.py")
	_ = os.WriteFile(f, []byte("# Auto Generated. DO NOT EDIT.\nprint('hi')\n"), 0o600)
	got, err := IsGeneratedFile(f, true)
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	if !got {
		t.Fatalf("expected true for python generated marker")
	}
}

func TestIsGeneratedFile_NoMarker(t *testing.T) {
	dir := t.TempDir()
	f := filepath.Join(dir, "x.ts")
	_ = os.WriteFile(f, []byte("// regular comment\nconsole.log('ok')\n"), 0o600)
	got, err := IsGeneratedFile(f, true)
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	if got {
		t.Fatalf("expected false for no marker")
	}
}
